# Generated by Django 2.1.2 on 2018-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='idno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='idno',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
