# Generated by Django 2.1.2 on 2018-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181127_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
    ]
